version: "3"

services:
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: money-processing
      POSTGRES_PASSWORD: money-processing
      POSTGRES_DB: money-processing
    ports:
      - "5432:5432"
    expose:
      - 5432

  server:
    image: seth2810/money_processing:develop
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: money-processing
      DB_PASSWORD: money-processing
      DB_NAME: money-processing
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure
