version: "3"

networks:
  db:
    driver: bridge
  server:
    driver: bridge

services:
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: money-processing
      POSTGRES_PASSWORD: money-processing
      POSTGRES_DB: money-processing
    command: postgres -c max_connections=350
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    networks:
      - db

  server:
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: money-processing
      DB_PASSWORD: money-processing
      DB_NAME: money-processing
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - db
      - server

  tests:
    build:
      context: .
      dockerfile: .docker/tests/Dockerfile
    environment:
      DB_DSN: "host=db port=5432 user=money-processing password=money-processing dbname=money-processing sslmode=disable"
    depends_on:
      - db
      - server
    links:
      - db
      - server
    networks:
      - db
      - server
