// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: clients.sql

package queries

import (
	"context"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (email) VALUES ($1) RETURNING id, email
`

func (q *Queries) CreateClient(ctx context.Context, email string) (*Client, error) {
	row := q.db.QueryRowContext(ctx, createClient, email)
	var i Client
	err := row.Scan(&i.ID, &i.Email)
	return &i, err
}

const getClient = `-- name: GetClient :one
SELECT id, email FROM clients WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClient(ctx context.Context, id int32) (*Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(&i.ID, &i.Email)
	return &i, err
}
